version: "3"
services:
  db:
    image: mysql
    command: --init-file /db.sql --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - type: bind
        source: ./controller/db.sql
        target: /db.sql
        read_only: true
    environment:
      MYSQL_ROOT_PASSWORD: Eruliz1987.

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - private
  node:
    depends_on:
    - db
    image: "node:10" # https://hub.docker.com/_/node/
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DB_URL=db
    env_file:
      - secrets.env # los _secrets_ a incluir como variables de entorno. Usa el archivo `sample.secrets.env` como guia
    volumes:
      - ./:/home/node/app # montamos el codigo en el HOME del usuario _node_
    expose:
      - "8080" # nuestra app corre en el puerto 8080
    ports:
      - "80:8080" # mapeamos el puerto 8080 de nuestro contenedor al puerto 80 de nuestra maquina
    command: "bash -c 'rm -rf node_modules && npm install && npm start'" # reinstalamos las dependencias y levantamos el servidor
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true
